// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2oFyAdZXNkTtEgblsGRgiub7MreOYubc',
    appId: '1:980918373051:web:a1ebe29245fd8fdc33f79e',
    messagingSenderId: '980918373051',
    projectId: 'swissproject-33b18',
    authDomain: 'swissproject-33b18.firebaseapp.com',
    storageBucket: 'swissproject-33b18.firebasestorage.app',
    measurementId: 'G-H604S11TN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMpxRv0_YtiPdJmMV8qbaFtGq3H0Zzzao',
    appId: '1:980918373051:android:d8034f81b7a5031a33f79e',
    messagingSenderId: '980918373051',
    projectId: 'swissproject-33b18',
    storageBucket: 'swissproject-33b18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpWi7kXafl0GC1c2q7xYa8qhYfKX0D7Dc',
    appId: '1:980918373051:ios:ff7f0eee4658015d33f79e',
    messagingSenderId: '980918373051',
    projectId: 'swissproject-33b18',
    storageBucket: 'swissproject-33b18.firebasestorage.app',
    iosBundleId: 'com.example.slsAdmin',
  );
}
